export const siteConfig = {
  name: "InoBux",
  url: "https://www.inobux.com",
  locale: "en_US",
  language: "en-US",
  author: "InoBux",
  contactEmail: "info@inobux.com",
  twitterSite: "@inobux",
  logoPath: "/logo1.png",
  defaultTitle: "InoBux | AI Development, Web Development, Mobile Apps, ERP, CRM & UI/UX",
  defaultDescription:
    "InoBux builds high-performance AI solutions, web platforms, mobile apps, ERP systems, CRM software, analytics experiences, and UI/UX design systems for modern businesses.",
  defaultKeywords: [
    "AI development company",
    "web development agency",
    "mobile app development",
    "ERP solutions",
    "CRM development",
    "data science services",
    "UI UX design",
    "React development",
    "chatbot integration",
    "Three.js website",
  ],
  socialProfiles: [
    "https://www.linkedin.com/company/inobux",
    "https://twitter.com/inobux",
  ],
  serviceTypes: [
    "Web Development",
    "Mobile App Development",
    "Data Science & Analytics",
    "AI Development",
    "UI/UX Design",
    "ERP Solutions",
    "CRM Development",
  ],
  routes: [
    { path: "/", changefreq: "weekly", priority: "1.0" },
    { path: "/blog/web-development-trends-2024", changefreq: "monthly", priority: "0.8", articleDate: "2023-12-15" },
    { path: "/blog/freelance-success-it", changefreq: "monthly", priority: "0.8", articleDate: "2023-12-12" },
    { path: "/blog/ui-ux-design-principles", changefreq: "monthly", priority: "0.8", articleDate: "2023-12-10" },
    { path: "/blog/react-native-cross-platform", changefreq: "monthly", priority: "0.8", articleDate: "2023-12-08" },
    { path: "/blog/data-analytics-business-growth", changefreq: "monthly", priority: "0.8", articleDate: "2023-12-05" },
    { path: "/blog/ecommerce-development-practices", changefreq: "monthly", priority: "0.8", articleDate: "2023-12-03" },
    { path: "/blog/cloud-devops-integration", changefreq: "monthly", priority: "0.8", articleDate: "2023-11-30" },
    { path: "/blog/digital-marketing-it-services", changefreq: "monthly", priority: "0.8", articleDate: "2023-11-28" },
    { path: "/blog/ai-machine-learning-applications", changefreq: "monthly", priority: "0.8", articleDate: "2023-11-25" },
    { path: "/blog/progressive-web-apps-future", changefreq: "monthly", priority: "0.8", articleDate: "2023-11-22" },
  ],
};
